International Seismological Centre
ISC: On-Line Bulletin

Any use of data from the ISC should be cited. The correct format for citations may be found on our citation page.

The ISC Bulletin has been rebuilt for the period 1964-1979. All ISC searches will now return the upgraded set of data for this period. The work on the Rebuild project continues for the period 1980-2010 and will result in further gradual bulletin updates in due time.

Once the search has completed, a compressed KML file will be available to view the results in Google Earth.

Make an event map

Search summary:
Database: ISC Bulletin
Search type: Circular search
Central latitude: -45.5
Central longtitude: -59
Radius: 2 degrees
Start date: 2017-11-15 00:00:00
End date: 2017-12-02 00:00:00
 Events found: 2
DATA_TYPE BULLETIN IMS1.0:short
ISC Bulletin
Event 611574053 South Atlantic Ocean

   Date       Time        Err   RMS Latitude Longitude  Smaj  Smin  Az Depth   Err Ndef Nsta Gap  mdist  Mdist Qual   Author      OrigID
2017/11/15 13:51:13.27  199.7 0.410 -46.1107  -59.6923 487.1  22.8  98   0.0f         3      283  53.36  69.64     uk IDC       09536329

Sta     Dist  EvAz Phase        Time      TRes  Azim AzRes   Slow   SRes Def   SNR       Amp   Per Qual Magnitude    ArrID
H10S3  53.36  60.6 H        14:58:03.423       218.5        73.60        ___                        __            46503853
H10S2  53.36  60.6 H        14:58:03.76          1.5        73.60        ___                        __            46503852
H10N3  54.33  59.9 H        14:59:16.191       217.0        75.40        ___                        __            46503851
H10N1  54.34  59.9 H        14:59:16.878       217.0        75.40        ___                        __            46503849
H10N2  54.35  59.9 H        14:59:17.619       217.0        75.40        ___                        __            46503850
H04S2  69.71 137.1 H        15:19:36.373       223.5        75.40        ___ 704.1                  __            46503847
H04S3  69.72 137.1 H        15:19:37.622       223.5        75.40        ___ 555.4                  __            46503848
H04S1  69.73 137.1 H        15:19:37.587       223.5        75.40        ___ 670.8                  __            46503846

Event 611604170 South Atlantic Ocean

   Date       Time        Err   RMS Latitude Longitude  Smaj  Smin  Az Depth   Err Ndef Nsta Gap  mdist  Mdist Qual   Author      OrigID
2017/12/01 20:04:55.19  210.5 0.020 -45.6185  -58.9208 515.1  23.0  98   0.0f         3      283  52.65  69.63     uk IDC       09558627

Sta     Dist  EvAz Phase        Time      TRes  Azim AzRes   Slow   SRes Def   SNR       Amp   Per Qual Magnitude    ArrID
H10S3  52.65  60.2 H        21:10:51.94        218.5        73.60        ___  27.0                  __            46916404
H10S2  52.65  60.2 H        21:10:52.109         1.5        73.60        ___   9.7                  __            46916403
H10N3  53.62  59.5 H        21:12:04.836       216.8        75.40        ___  25.1                  __            46916402
H10N1  53.62  59.5 H        21:12:05.195       216.8        75.40        ___  34.0                  __            46916400
H10N2  53.63  59.5 H        21:12:05.456       216.8        75.40        ___  32.6                  __            46916401
H04S2  69.70 136.8 H        21:32:51.362       224.4        75.30        ___   7.1                  __            46916398
H04S3  69.71 136.8 H        21:32:59.194       224.4        75.30        ___   5.9                  __            46916399
H04S1  69.72 136.8 H        21:32:59.876       224.4        75.30        ___   5.6                  __            46916397


STOP

International Seismological Centre
Pipers Lane, Thatcham, Berkshire
United Kingdom RG19 4NS
+44 (0)1635 861022, voice; +44 (0)1635 872351, fax
adminisc.ac.uk, e-mail
