Event 10761 Eastern Caucasus
   Date       Time        Err   RMS Latitude Longitude  Smaj  Smin  Az Depth   Err Ndef Nsta Gap  mdist  Mdist Qual   Author      OrigID    Rep   DPdep   Err Sgp
2006/11/21 17:12:52.22   0.59  0.95  43.5334   45.9757   7.7   4.7  16 129.8   6.1   69    0  70   0.67  13.10     ke ISC       10484745
2006/11/21 17:12:51.50   0.22  1.00  43.5310   45.9898   5.8   3.2   6 127.7   3.0   39    0  75   0.66  13.10     ke CSEM      10432676
2006/11/21 17:12:51.58   0.56  0.94  43.5324   45.9677   7.7   4.6  18 131.9   5.8   69    0  70   0.67  13.10     ke ISCJB     10605396
2006/11/21 17:12:51.60   0.66        43.5270   45.9240  10.4   9.4  18 132.0         25    0                          MOS       9868767
 (#PRIME)

Magnitude  Err Nsta Author      OrigID
mb     4.4          CSEM      10432676
mb     4.4        1 MOS        9868767

Sta     Dist  EvAz Phase        Time      TRes  Azim AzRes   Slow   SRes Def   SNR       Amp   Per Qual Magnitude    ArrID    Agy   Deploy   Ln Auth  Rep   PCh ACh L
TRKR    0.75 276.1 Pn       17:13:15.500                                 T__                       __i            34526262    FDSN  IR       -- BUD   ISC   ??? ??? _
TRKR    0.75 276.1 Sn       17:13:32.700  11.6                           T__                       __i            34526263    FDSN  IR       -- BUD   ISC   ??? ??? _
DLMR    0.86 131.9 Pn       17:13:11.500   1.4                           T__                       __i            24264564    FDSN  IR       -- BUD   ISC   ??? ??? _
DLMR    0.86 131.9 Sn       17:13:27.000   3.1                           T__                       __i            34526240    FDSN  IR       -- BUD   ISC   ??? ??? _
SNJR    0.90 230.2 Pn       17:13:15.600   5.2                           T__                       __i            34526260    FDSN  IR       -- BUD   ISC   ??? ??? _
SNJR    0.90 230.2 Sn       17:13:33.000   8.5                           T__                       __i            34526261    FDSN  IR       -- BUD   ISC   ??? ??? _
VLKR    0.99 233.0 Pn       17:13:16.300   4.6                           T__                       __i            34526266    FDSN  IR       -- BUD   ISC   ??? ??? _
VLKR    0.99 233.0 Sn       17:13:34.300   7.8                           T__                       __i            34526267    FDSN  IR       -- BUD   ISC   ??? ??? _
DBC     1.00 128.3 Pg       17:13:13.700   0.9                           T__                       _di            24264567    FDSN  IR       -- BUD   ISC   ??? ??? _
DBC     1.00 128.3 Sn       17:13:30.000   2.2                           T__                       __i            34526234    FDSN  IR       -- BUD   ISC   ??? ??? _
BTLR    1.04 160.7 Pg       17:13:13.500   0.3                           T__                       __e            24264572    FDSN  IR       -- BUD   ISC   ??? ??? _
BTLR    1.04 160.7 Sn       17:13:29.500   1.3                           T__                       __i            34526230    FDSN  IR       -- BUD   ISC   ??? ??? _
PRTR    1.07 276.0 Pn       17:13:18.200   5.3                           T__                       __i            34526257    FDSN  IR       -- BUD   ISC   ??? ??? _
PRTR    1.07 276.0 Sn       17:13:37.500   8.9                           T__                       __i            34526258    FDSN  IR       -- BUD   ISC   ??? ??? _
ARNR    1.17 246.9 Pn       17:13:18.500   4.4                           T__                       __i            34526227    FDSN  IR       -- BUD   ISC   ??? ??? _
ARNR    1.17 246.9 Sn       17:13:37.000   6.4                           T__                       __i            34526228    FDSN  IR       -- BUD   ISC   ??? ??? _
KRNR    1.18 133.9 Pn       17:13:14.500  -0.3                           T__                       _ci            24264577    FDSN  IR       -- BUD   ISC   ??? ??? _
KRNR    1.18 133.9 Sn       17:13:32.000   0.1                           T__                       __i            34526246    FDSN  IR       -- BUD   ISC   ??? ??? _
UNCR    1.20 140.5 Pn       17:13:14.500  -0.4                           T__                       __i            24264582    FDSN  IR       -- BUD   ISC   ??? ??? _
UNCR    1.20 140.5 Sn       17:13:32.000  -0.1                           T__                       __i            34526265    FDSN  IR       -- BUD   ISC   ??? ??? _
BUJR    1.29 129.3 Pn       17:13:16.000  -0.1                           T__                       __e            24264585    FDSN  IR       -- BUD   ISC   ??? ??? _
BUJR    1.29 129.3 Sn       17:13:35.000   0.8                           T__                       __i            34526232    FDSN  IR       -- BUD   ISC   ??? ??? _
LACR    1.34 232.9 Pn       17:13:18.900   2.2                           T__                       __i            34526248    FDSN  IR       -- BUD   ISC   ??? ??? _
LACR    1.34 232.9 Sn       17:13:37.800   2.6                           T__                       __i            34526249    FDSN  IR       -- BUD   ISC   ??? ??? _
KORR    1.35 246.0 Pn       17:13:19.800   3.2                           T__                       __i            34526243    FDSN  IR       -- BUD   ISC   ??? ??? _
KORR    1.35 246.0 Sn       17:13:40.300   5.4                           T__                       __i            34526244    FDSN  IR       -- BUD   ISC   ??? ??? _
MAK     1.45 117.7 Pg       17:13:21.200  -0.2                           T__                       __i            24264592    FDSN  IR       -- BUD   ISC   ??? ??? _
MAK     1.45 117.7 Lg       17:13:41.900   0.2                           T__                       __e            34526251    FDSN  IR       -- BUD   ISC   ??? ??? _
ZEI     1.60 238.2 Pg       17:13:21.800  -0.7                           T__                       __i            34526268    FDSN  IR       -- BUD   ISC   ??? ??? _
ZEI     1.60 238.2 Sn       17:13:42.700   0.9                           T__                       __i            34526269    FDSN  IR       -- BUD   ISC   ??? ??? _
KUBR    1.71 275.9 Pg       17:13:24.300  -0.3                           T__                       __i            34526247    FDSN  IR       -- BUD   ISC   ??? ??? _
DUS     1.74 206.8 Pn       17:13:23.781   1.6                           T__                       ___            33006336    FDSN  IR       -- BUD   ISC   ??? ??? _
DUS     1.74 206.8 Lg       17:13:47.200  -2.1                           T__                       ___            33006337    FDSN  IR       -- BUD   ISC   ??? ??? _
DIGR    1.76 245.5 Pg       17:13:23.700  -1.3                           T__                       __i            34526237    FDSN  IR       -- BUD   ISC   ??? ??? _
DIGR    1.76 245.5 Sn       17:13:46.100   0.9                           T__                       __i            34526238    FDSN  IR       -- BUD   ISC   ??? ??? _
PYA     1.99 282.1 Pn       17:13:27.100   1.7                           T__                       __i            24264610    FDSN  IR       -- BUD   ISC   ??? ??? _
ONI     1.99 238.7 Pg       17:13:27.000  -1.8                           T__                       ___            34526255    FDSN  IR       -- BUD   ISC   ??? ??? _
ONI     1.99 238.7 Sn       17:13:52.500   2.7                           T__                       ___            34526256    FDSN  IR       -- BUD   ISC   ??? ??? _
MTA     2.08 200.3 Pg       17:13:36.200   3.3                           T__                       ___            34526252    FDSN  IR       -- BUD   ISC   ??? ??? _
MTA     2.08 200.3 Lg       17:14:01.600   1.3                           T__                       ___            34526253    FDSN  IR       -- BUD   ISC   ??? ??? _
DGRG    2.21 187.5 Pn       17:13:29.100  -0.2                           T__                       ___            34526235    FDSN  IR       -- BUD   ISC   ??? ??? _
DGRG    2.21 187.5 Sn       17:13:55.800  -1.0                           T__                       ___            34526236    FDSN  IR       -- BUD   ISC   ??? ??? _
KIV     2.24 278.9 Pn       17:13:30.300   1.4                           T__                       _ci            24264611    FDSN  IR       -- BUD   ISC   ??? ??? _
KZR     2.47 204.1 Pn       17:13:31.586  -1.2                           T__                       ___            33006338    FDSN  IR       -- BUD   ISC   ??? ??? _
KZR     2.47 204.1 Sn       17:14:01.886  -0.7                           T__                       ___            33006339    FDSN  IR       -- BUD   ISC   ??? ??? _
GNI     3.58 192.6 Pn       17:13:46.500  -1.7                           T__                       __i            34526241    FDSN  IR       -- BUD   ISC   ??? ??? _
ANN     6.09 283.8 Pn       17:14:24.300   1.8                           T__                       __e            24264613    FDSN  IR       -- BUD   ISC   ??? ??? _
ANN     6.09 283.8 Sn       17:15:33.400   0.7                           T__                       __e            34526226    FDSN  IR       -- BUD   ISC   ??? ??? _
AKTO   10.77  46.6 Pn       17:15:21.484  -1.7                           T__             0.1  0.85 _d_        0.0 09709005    FDSN  IR       -- BUD   ISC   ??? ??? _
AKTO   10.77  46.6 Sn       17:17:14.831  -2.1                           T__                       _d_            09709006    FDSN  IR       -- BUD   ISC   ??? ??? _
AB31   11.27  55.2 Pn       17:15:28.214  -1.7 248.4   2.9  12.00   -1.6 TA_             0.9  0.55 _c_        0.0 09709003    FDSN  IR       -- BUD   ISC   ??? ??? _
AB31   11.27  55.2 Sn       17:17:25.812  -1.0 246.2   0.7  24.10    0.3 TA_            11.4  0.65 _d_        0.0 09709004    FDSN  IR       -- BUD   ISC   ??? ??? _
OBN    12.93 335.8 Pn       17:15:53.200   0.8                           T__                       __e            24264616    FDSN  IR       -- BUD   ISC   ??? ??? _

